enhancement:
  - branch:
      - pattern: "feature/**"
      - pattern: "feat/**"

chore:
  - branch:
      - pattern: "chore/**"

performance:
  - branch:
      - pattern: "performance/**"
      - pattern: "*blazingly-fast*"

refactor:
  - branch:
      - pattern: "refactor/**"

documentation:
  - branch:
      - pattern: "docs/**"

dependencies:
  - branch:
      - pattern: "renovate/**"
      - pattern: "deps/**"

bug:
  - branch:
      - pattern: "fix/**"
      - pattern: "bugfix/**"
