enhancement: ["feature/*", "feat/*"]
chore: ["chore/*"]
performance: ["performance/*", "*blazingly-fast*"]
refactor: ["refactor/*"]
documentation: ["docs/*"]
dependencies: ["renovate/*", "deps/"]
bug: ["fix/*", "bugfix/*"]
