enhancement: ["feature/*", "feat/*"]
ignore: ["bump/version*"]
chore: ["chore/*"]
performance: ["performance/*", "*blazingly-fast*"]
refactor: ["refactor/*"]
documentation: ["docs/*"]
dependencies: ["renovate/*"]
bug: ["fix/*", "bugfix/*"]
