change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: ":boom: Breaking Changes"
    label: "breaking-change"

  - title: ":sparkles: New Features"
    label: "enhancement"

  - title: ":bug: Bug Fixes"
    labels:
      - "bug"
      - "bugfix"

  - title: ":boar: Chore"
    label: "chore"

  - title: ":zap: Performance"
    label: "performance"

  - title: ":recycle: Refactor"
    label: "refactor"

  - title: ":white_check_mark: Test"
    label: "test"

  - title: ":arrow_up: Dependency Updates"
    label: "dependencies"
    collapse-after: 1

template: |

  $CHANGES
