change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

category-template: "### $TITLE"
categories:
  - title: ":boom: Breaking Changes"
    label: "breaking-change"

  - title: ":sparkles: New Features"
    label: "enhancement"

  - title: ":bug: Bug Fixes"
    labels:
      - "bug"
      - "bugfix"

  - title: ":boar: Chore"
    label: "chore"

  - title: ":zap: Performance"
    label: "performance"

  - title: ":recycle: Refactor"
    label: "refactor"

  - title: ":white_check_mark: Test"
    label: "test"

  - title: ":arrow_up: Dependency Updates"
    label: "dependencies"
    collapse-after: 1

header: |

  ## What's Changed

template: |

  $CHANGES

footer: |

  ## Auditable binaries since v0.8.x
  The binaries built for desktop targets are now all build in auditable mode using [cargo-auditable](https://github.com/rust-secure-code/cargo-auditable?tab=readme-ov-file#cargo-auditable).
  For information on how to audit the binaries see [Usage](https://github.com/rust-secure-code/cargo-auditable?tab=readme-ov-file#usage)

  ## Attested build artifacts since v0.8.x
  The build artifacts are now attested. Attestations information about he binaries is available [here](https://github.com/hrzlgnm/mdns-browser/attestations). For more information and details on how to verify those, see [Verifying artifact attestations with the GitHub CLI](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#verifying-artifact-attestations-with-the-github-cli)
