change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

category-template: "### $TITLE"
categories:
  - title: ":boom: Breaking Changes"
    label: "breaking-change"

  - title: ":sparkles: New Features"
    label: "enhancement"

  - title: ":bug: Bug Fixes"
    labels:
      - "bug"
      - "bugfix"

  - title: "🧰 Maintenance"
    label: "chore"

  - title: ":zap: Performance"
    label: "performance"

  - title: ":recycle: Refactor"
    label: "refactor"

  - title: ":scroll: Documentation"
    label: "documentation"

  - title: ":white_check_mark: Test"
    label: "test"

  - title: ":arrow_up: Dependency Updates"
    label: "dependencies"
    collapse-after: 1

exclude-labels:
  - ignore

header: |

  ## What's Changed

template: |

  $CHANGES
