[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [".git/", ".github/cliff/cliff.toml", ".github/cliff/cliff-webkit2gtk.toml", ".github/cliff/cliff-tauri-plugin-android-update.toml", ".github/cliff/cliff-release.toml"]

[default]
check-filename = true
extend-ignore-re = ["digest to \\b[0-9a-f]{7,}\\b"]
