[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [".git/", "cliff.toml", "cliff-webkit2gtk.toml", ".github/cliff-release.toml"]

[default]
check-filename = true
extend-ignore-re = ["digest to \\b[0-9a-f]{7,}\\b"]
