name: Create and scan sbom action
description: Creates and scans the sbom for security vulnerabilities

inputs:
  artifact-name:
    description: "The name of the sbom upload artifact"
    required: false

runs:
  using: "composite"
  steps:
    - name: 📜 Create SBOM
      uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0
      env:
        SYFT_SOURCE_NAME: ${{ github.event.repository.name }}
        SYFT_SOURCE_VERSION: ${{ steps.get-version.outputs.current-version }}
      with:
        format: "spdx-json"
        output-file: "sbom.spdx.json"
        artifact-name: ${{ inputs.artifact-name }}

    - name: 🔍 Scan SBOM
      id: scan
      uses: anchore/scan-action@3aaf50d765cfcceafa51d322ccb790e40f6cd8c5 # v7.2.0
      with:
        sbom: "sbom.spdx.json"
        severity-cutoff: medium
        cache-db: true

    - name: 🔍 Inspect SARIF report
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        jq ${{ steps.scan.outputs.sarif }}

    - name: 🔍 Inspect SARIF report
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        jq ${{ steps.scan.outputs.sarif }}
