[package]
name = "tauri-plugin-android-updater"
version = "0.1.0"
description = "Android auto-update support for mdns-browser"
authors = ["hrzlgnm"]
edition = "2021"
links = "tauri-plugin-android-updater"

[build-dependencies]
tauri-build = { version = "2.2", features = [] }
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
# crates
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tauri-plugin-http = { workspace = true }
thiserror = { workspace = true }

# local
models = { path = "../models" }
