# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Setup sccache
description: Sets up sccache

runs:
  using: "composite"
  steps:
    - uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

    - shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=${SCCACHE_PATH}" >> $GITHUB_ENV
