# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT

name: Setup sccache
description: Sets up sccache

runs:
  using: "composite"
  steps:
    - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

    - shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=${SCCACHE_PATH}" >> $GITHUB_ENV
