# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT

name: Setup tauri
description: Sets up tauri

runs:
  using: "composite"
  steps:
    - name: Install trunk
      uses: ./.github/actions/install-cargo-tool
      with:
        crate: trunk
        version: 0.21.14
        args: --no-default-features
        features: rustls

    - name: Install cargo-auditable
      uses: ./.github/actions/install-cargo-tool
      with:
        crate: cargo-auditable
        version: 0.7.5

    - name: Install tauri-cli
      uses: ./.github/actions/install-cargo-tool
      with:
        crate: tauri-cli
        version: 2.11.4
