# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT

name: Setup tauri
description: Sets up tauri

runs:
  using: "composite"
  steps:
    - uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759 # v3
      with:
        crate: cargo-auditable
        version: 0.7.6
        locked: true

    - uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759 # v3
      with:
        crate: tauri-cli
        version: 2.11.4
        locked: true
