// GENERATED by ts-rs — do not edit. Regenerate with scripts/export-types.sh.
export type ServiceTypes = Array<string>;
export type TxtRecord = { key: string, val: string | null, };
export type InterfaceScope = { name: string, index: number, };
export type ScopedAddr = { addr: string, interfaces: Array<InterfaceScope>, scope_id?: string | null, };
export type ResolvedService = { instance_fullname: string, service_type: string, hostname: string, port: number, addresses: Array<ScopedAddr>, subtype: string | null, txt: Array<TxtRecord>, updated_at_micros: string, dead: boolean, };
export type NetworkInterface = { name: string, addresses: Array<string>, enabled: boolean, };
export type InterfacesChangedEvent = { interfaces: Array<NetworkInterface>, };
export type MetricsChangedEvent = { metrics: { [key in string]: number }, };
export type ServiceResolvedEvent = { service: ResolvedService, };
export type ServiceTypeFoundEvent = { service_type: string, };
export type ServiceRemovedEvent = { instance_name: string, at_micros: string, };
export type ThemeChangedEvent = { theme: string, };
export type ProtocolFlags = { ipv4: boolean, ipv6: boolean, };
export type UpdateMetadata = { version: string, currentVersion: string, };
