# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable android workflow"

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: ""
      tagName:
        required: false
        type: string
    secrets:
      ANDROID_RELEASE_KEYSTORE:
        required: false
      ANDROID_RELEASE_KEYSTORE_PASSWORD:
        required: false
      ANDROID_RELEASE_KEY:
        required: false
      ANDROID_RELEASE_KEY_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: 📦🔨
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.tagName || github.ref }}
          fetch-depth: ${{ inputs.tagName && '0' || '1' }}
      - name: 📝 Extract version from tauri.android.conf.json
        id: get-version
        run: |
          CURRENT_VERSION=$(jq -r '.version' src-tauri/tauri.android.conf.json)
          echo "current-version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: 🛡️ Verify tag matches version in tauri config (publish only)
        if: inputs.tagName
        shell: bash
        run: |
          CURRENT_VERSION=${{ steps.get-version.outputs.current-version }}
          TAG=${{ inputs.tagName }}
          if [[ "$TAG" != *"$CURRENT_VERSION" ]]
          then
            echo "The tag name ${TAG} does not match the version ${CURRENT_VERSION} from tauri config"
            exit 1
          fi

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android,wasm32-unknown-unknown
          save-cache: ${{ inputs.branch == 'main' }}

      - name: 📜 Create and 🔍 scan SBOM for vulnerabilities
        if: inputs.tagName
        uses: ./.github/actions/sbom
        with:
          artifact-name: "sbom.android.spdx.json"
          current-version: ${{ steps.get-version.outputs.current-version }}

      - name: 🛠️🐂
        uses: ./.github/actions/setup-tauri

      - name: 🛠️🚀
        if: (!inputs.tagName)
        uses: ./.github/actions/setup-sccache

      - name: ☕ Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 🤖 Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4

      - name: 🛠️ Install NDK
        run: sdkmanager "ndk;27.0.11902837"

      - name: 🔨 Build app bundle
        run: |
          cargo --locked auditable tauri android init
          cp -a src-tauri/icons/android/mipmap-* src-tauri/gen/android/app/src/main/res/
          cargo --locked auditable tauri android build
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837
          RUSTFLAGS: "-D warnings"

      - name: 🔑 Extract android signing key
        env:
          ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
        run: |
          echo "$ANDROID_RELEASE_KEYSTORE" > src-tauri/gen/android/release.jks.base64
          base64 -d src-tauri/gen/android/release.jks.base64 > src-tauri/gen/android/release.decrypted.jks

      - name: 🔏 Sign APK
        env:
          ANDROID_RELEASE_KEY: ${{ secrets.ANDROID_RELEASE_KEY }}
          ANDROID_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
          ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
        run: |
          "${{ env.ANDROID_HOME }}/build-tools/34.0.0/apksigner" sign --ks src-tauri/gen/android/release.decrypted.jks \
            --ks-key-alias "$ANDROID_RELEASE_KEY" \
            --ks-pass "pass:$ANDROID_RELEASE_KEYSTORE_PASSWORD" \
            --key-pass "pass:$ANDROID_RELEASE_KEY_PASSWORD" \
            --out src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk \
            src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

      - name: 📤 Upload build artifacts (if not publishing)
        if: (!inputs.tagName)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "signed-apk"
          path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk

      - name: ✏️ Rename APK file
        run: |
          mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk ./src-tauri/gen/android/app/build/outputs/apk/universal/release/mdns-browser_${{ steps.get-version.outputs.current-version }}.apk

      - name: 🚀 Publish (publish only)
        if: inputs.tagName
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          name: mDNS-Browser Release v${{ steps.get-version.outputs.current-version }}
          tag_name: ${{ inputs.tagName }}
          append_body: true
          make_latest: false
          generate_release_notes: false
          files: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/mdns-browser_${{ steps.get-version.outputs.current-version }}.apk

      - name: 🛡️ Attest build provenance (publish only)
        if: inputs.tagName
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/mdns-browser_${{ steps.get-version.outputs.current-version }}.apk

      - name: 🛡️ Attest SBOM (publish only)
        if: inputs.tagName
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-path: src-tauri/gen/android/app/build/outputs/apk/universal/release/mdns-browser_${{ steps.get-version.outputs.current-version }}.apk
          sbom-path: "sbom.spdx.json"
