name: "📱"

on:
  pull_request:
    paths-ignore:
      - ".zed/**"
      - "**/*.md"
      - ".coderabbitai.yaml"
      - ".github/*.yml"
      - ".github/docker/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/renovate.json5"
      - ".github/workflows/bump-*"
      - ".github/workflows/docker-*"
      - ".github/workflows/pr-label*"
      - ".github/workflows/*publish*"
      - ".github/workflows/release-*"
      - ".github/workflows/void-*"
      - ".github/workflows/winget-*"
      - "aur-template/**"
      - "screenshots/**"
      - "xbps-template/**"
    branches:
      - main

concurrency:
  group: ${{ format('android-{0}', github.ref) }}
  cancel-in-progress: true
jobs:
  pr:
    permissions:
      contents: write
    uses: ./.github/workflows/android.yml
    secrets: inherit
