# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable cache tools for release workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cache-tools:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          save-cache: false

      # Ensure tools used in release workflow are in the cache

      - name: 🔧 Install cargo-edit
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: cargo-edit
          version: 0.13.9
          locked: true

      - name: 🔧 Install komac
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: komac
          version: 2.16.0
          locked: true

  cache-platform-tools:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            symbol: 🐧
            platform: Linux
            container_image: ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1@sha256:3d1f37dc82c523e80b700abdc7a6110c8542d5c02ce5f0d4e7198a6bfee13159
          - os: "macos-latest"
            args: "--target universal-apple-darwin"
            symbol: 🍏
            platform: macOS
          - os: "windows-latest"
            symbol: 🪟
            platform: Windows

    name: ${{matrix.symbol}}🔨
    runs-on: ${{matrix.os}}
    steps:
      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin,wasm32-unknown-unknown' || 'wasm32-unknown-unknown' }}
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: 🛠️🐂
        uses: ./.github/actions/setup-tauri
