# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable cache tools for release workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cache-cargo-edit:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          save-cache: false

      # Ensure tools used in release workflow are in the cache

      - name: 🔧 Install cargo-edit
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: cargo-edit
          version: 0.13.9
          locked: true

      - name: 🔧 Install komac
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: komac
          version: 2.15.0
          locked: true
