name: "🖥️"

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".coderabbitai.yaml"
      - ".github/*.yml"
      - ".github/docker/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/renovate.json5"
      - ".github/workflows/bump-*"
      - ".github/workflows/docker-*"
      - ".github/workflows/pr-label*"
      - ".github/workflows/*publish*"
      - ".github/workflows/release-*"
      - ".github/workflows/void-*"
      - ".github/workflows/winget-*"
      - "aur-template/**"
      - "screenshots/**"
      - "xbps-template/**"
    branches:
      - main

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('dekstop-main-{0}', github.sha) || format('dekstop-{0}', github.ref) }}

jobs:
  lint:
    uses: ./.github/workflows/ci-lint.yml
  test:
    uses: ./.github/workflows/ci-test.yml
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/desktop-tauri.yml
    secrets: inherit
