name: "Desktop Push"

on:
  push:
    branches:
      - main

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('dekstop-main-{0}', github.sha) || format('dekstop-{0}', github.ref) }}

jobs:
  push:
    permissions:
      contents: write
    uses: ./.github/workflows/desktop-tauri.yml
    secrets: inherit
