# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci lint workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          components: rustfmt

      - name: 📐 Run rustfmt and fail if any warnings
        shell: bash
        run: |
          cargo fmt -- --check
          cd src-tauri
          cargo fmt -- --check

  leptosfmt:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 📥 Cached install leptosfmt
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: leptosfmt
          version: 0.1.33
          locked: true

      - name: 📐 Run leptosfmt and fail if any warnings
        run: |
          leptosfmt --check src

  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            symbol: 🐧
            platform: Linux
            container_image: ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1@sha256:36341feb9ccb9731af52ab5e96ddfef84e63876179c33996ca96c4ca4c2d4136
          - os: "macos-latest"
            symbol: 🍏
          - os: "windows-latest"
            symbol: 🪟
    runs-on: ${{matrix.os}}
    name: ${{matrix.symbol}}📎
    container: ${{ contains(matrix.os, 'ubuntu') && matrix.container_image || null }}
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          components: clippy
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin,wasm32-unknown-unknown' || 'wasm32-unknown-unknown' }}

      - name: 🛠️🚀
        uses: ./.github/actions/setup-sccache

      - name: 📎 Run clippy and fail if any warnings
        shell: bash
        run: |
          cargo clippy --workspace --tests -- -D warnings
