# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Publish tauri-plugin-android-update

on:
  workflow_dispatch:
    inputs:
      bump_version:
        description: Version bump type
        required: true
        type: choice
        options:
          - none
          - patch
          - minor
          - major
        default: patch
      dry-run:
        description: Dry run (no commits/tags/releases)
        required: true
        type: boolean
        default: false
      publish:
        description: Publish to crates.io after version bump
        required: true
        type: boolean
        default: true

jobs:
  publish:
    uses: ./.github/workflows/publish-crate-reusable.yml
    with:
      bump_version: ${{ inputs.bump_version }}
      dry_run: ${{ inputs.dry-run }}
      publish: ${{ inputs.publish }}
      crate_name: tauri-plugin-android-update
      tag_prefix: tauri-plugin-android-update-v
      git_cliff_config: cliff-tauri-plugin-android-update.toml
    secrets:
      GH_ADMIN_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
      RULESET_ID: ${{ secrets.RULESET_ID }}
      SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
