# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Publish SBOM to release
on:
  workflow_call:
    inputs:
      tagName:
        description: The tag name of release to publish for
        type: string
        required: false

permissions:
  contents: write # Needed to upload SBOMs to release

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-slim
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 🏷️
        id: tag
        env:
          TAG_NAME: ${{ inputs.tagName }}
        run: |
          if [ -n "$TAG_NAME" ]; then
            echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"
          else
            echo "No tag provided" && exit 1
          fi

  publish:
    name: 📰📜
    runs-on: ubuntu-slim
    needs:
      - tag
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: 📥 SBOM artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: sboms
          pattern: sbom.*
          merge-multiple: true

      - name: 📰📜
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ needs.tag.outputs.tag }}
        run: |
          SBOMS=()
          while IFS= read -r -d '' file; do
            SBOMS+=("$file")
          done < <(find sboms -type f -name '*.spdx.json' -print0)
          if [ "${#SBOMS[@]}" -eq 0 ]; then
            echo "No SBOM files to upload"
            exit 1
          fi
          gh release upload "$TAG_NAME" "${SBOMS[@]}" --clobber
