# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Publish SBOM to release
on:
  workflow_call:
    inputs:
      tagName:
        description: The tag name of release to publish for
        type: string
        required: false

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-slim
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 🏷️
        id: tag
        env:
          TAG_NAME: ${{ inputs.tagName }}
        run: |
          if [ -n "$TAG_NAME" ]; then
            echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"
          else
            echo "No tag provided" && exit 1
          fi

  publish:
    name: 📰📜
    runs-on: ubuntu-slim
    needs:
      - tag
    steps:
      - name: 📥 SBOM artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: sboms
          pattern: sbom.*
          merge-multiple: true

      - name: 📰📜
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          append_body: true
          make_latest: false
          generate_release_notes: false
          files: |
            sboms/*
