# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Retry Failed CI

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  retry-failed:
    uses: hrzlgnm/actions/.github/workflows/retry-failed-ci-reusable.yml@8c6f0744eb0550008dfe4d671445d44a9ab72fd0 # v2.5.4
    permissions:
      actions: write
      contents: read
    with:
      workflow: ci.yml
      hours: 24
