# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Retry Failed CI

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  retry-failed:
    uses: hrzlgnm/actions/.github/workflows/retry-failed-ci-reusable.yml@1847f299d36e715acd93d4bc496b9faab29a4c94 # v2.6.0
    permissions:
      actions: write
      contents: read
    with:
      workflow: ci.yml
      hours: 24
