# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT

name: Retry Failed CI

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  retry-failed:
    uses: hrzlgnm/actions/.github/workflows/retry-failed-ci-reusable.yml@c8da22dbc24d2b2602dd99a730693c064337535b # v2.8.1
    permissions:
      actions: write
      contents: read
    with:
      workflow: ci.yml
      hours: 24
