# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Create and publish source checksum
on:
  workflow_call:
    inputs:
      tagName:
        description: The tag name of release to publish for
        type: string
        required: false
      semver:
        description: The semver of release to publish for
        type: string
        required: false

permissions:
  contents: write # Needed to upload checksums and publish release assets

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-slim
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 🏷️
        id: tag
        run: |
          if [ -n "${{ inputs.tagName }}" ]; then
            echo "tag=${{ inputs.tagName }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ inputs.semver }}" ]; then
            echo "tag=v${{ inputs.semver }}" >> "$GITHUB_OUTPUT"
          else
            echo "No tag provided" && exit 1
          fi

  generate_checksums:
    name: 🔢☑️
    runs-on: ubuntu-slim
    needs:
      - tag
    strategy:
      matrix:
        algorithm: [sha256]
    steps:
      - name: 📥🔢☑️
        run: |
          set -o errexit
          mkdir -p downloads && cd downloads
          curl -sLO https://github.com/hrzlgnm/mdns-browser/archive/refs/tags/${{ needs.tag.outputs.tag }}.tar.gz
          curl -sLO https://github.com/hrzlgnm/mdns-browser/archive/refs/tags/${{ needs.tag.outputs.tag }}.zip
          for file in *; do
            if [ -f "$file" ] && [[ "$file" != *.sha* ]]; then
              ${{ matrix.algorithm }}sum "$file" > "$file.${{ matrix.algorithm }}"
            fi
          done
      - name: 📤
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ matrix.algorithm }}-source-checksums
          path: "downloads/*.${{ matrix.algorithm }}"

  publish:
    name: 📰🔢☑️
    runs-on: ubuntu-slim
    needs:
      - tag
      - generate_checksums
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: 📥 artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8

      - name: 📰🔢☑️
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ needs.tag.outputs.tag }}
        run: |
          CHECKSUMS=()
          while IFS= read -r -d '' file; do
            CHECKSUMS+=("$file")
          done < <(find . -type f -name '*.sha*' -not -path './.git/*' -print0)
          if [ "${#CHECKSUMS[@]}" -eq 0 ]; then
            echo "No checksum files to upload"
            exit 1
          fi
          gh release upload "$TAG_NAME" "${CHECKSUMS[@]}" --clobber
