# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: Publish Desktop Release to WinGet

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    permissions:
      contents: read # needed to checkout repository for release info
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: 🏷️ Get latest release info
        id: release-info
        uses: ./.github/actions/latest-release-info

      - name: 🛠️ Get latest installer url 🔗
        shell: bash
        run: |
          TAG_NAME="${{ steps.release-info.outputs.tagName }}"
          VERSION="${{ steps.release-info.outputs.version }}"
          URL="https://github.com/hrzlgnm/mdns-browser/releases/download/${TAG_NAME}/mdns-browser_${VERSION}_x64-setup.exe"
          echo "URL=$URL" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Detected latest tag name: $TAG_NAME"
          echo "URL: $URL"
          echo "Version: $VERSION"

      - name: 🦀🚀
        uses: ./.github/actions/setup-rust-cache
        with:
          save-cache: false

      - name: 🔧 Install komac
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: komac
          version: 2.16.0
          locked: true

      - name: 🆙 sync our fork of winget-pkgs
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          komac sync-fork

      - name: 🆙 winget package
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          komac update hrzlgnm.mdns-browser \
            --version "$VERSION" \
            --urls "$URL" \
            --submit

      - name: 🧹 Cleanup merged branches
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          komac cleanup --only-merged
